
# Used for development
version: '3.1'

services:
  todo-app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=todo_app
    networks:
      - todo-network

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - tnqv:/var/lib/mysql
    ports:
      - 10001:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: todo_app
      MYSQL_PORT: 3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  tnqv: